<?php

/**
 * @file
 * Entityqueue alter module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\elx_user\Utility\UserUtility;

/**
 * Implements hook_form_alter().
 */
function trlx_entityqueue_alter_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {

    case 'entity_subqueue_spotlight_edit_form':
    case 'entity_subqueue_insider_corner_hompage_edit_form':
      $form['#prefix'] = "<div class='entityqueue-help-text'>Maximum 4 items
       can be added.";
      $form['#suffix'] = "</div>";
      unset($form['actions']['reverse']);
      unset($form['actions']['shuffle']);
      unset($form['actions']['clear']);
      break;
  }
}

/**
 * Implements hook_link_alter().
 */
function trlx_entityqueue_alter_link_alter(&$variables) {
  if ($variables['text'] == 'Entityqueues') {
    $variables['text'] = 'Homepage Content';
  }
}
