<?php

/**
 * @file
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function elx_custom_user_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dmc_mbo_migrate module.
    case 'help.page.dmc_mbo_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DMC-MBO custom migrate module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param array $form
 * @param array FormStateInterface $form_state
 * @param string $form_id
 */
function elx_custom_user_migrate_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_best_sellers_form':
      unset($form['field_best_sellers_three']['widget'][0]['top']['paragraph_type_title']['info']);
      unset($form['field_best_sellers_four']['widget'][0]['top']['paragraph_type_title']['info']);

    default:
  }
}
