<?php

/**
 * @file
 * Module file for the ELC Password Policy module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for user_form().
 */
function elc_password_policy_form_user_form_alter(&$form, &$form_state) {
  $form['#validate'][] = 'password_policy_user_profile_form_validate';
}

/**
 * Check if password policies failed.
 *
 * @param mixed $form
 *   Form definition for the user profile form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state of the user profile form.
 *
 * @return bool
 *   Whether or not the password passes the user's constraints.
 */
function password_policy_user_profile_form_validate(&$form, FormStateInterface &$form_state) {
  $pass = $form_state->getValue('pass');
  if (!empty($pass)) {
    $not_valid = password_policy_constraints_validate($pass);
    if ($not_valid) {
      $form_state->setErrorByName('pass', $not_valid);
    }
  }
}

/**
 * Validate password policy constraints.
 *
 * @param mixed $pass
 *   Form definition to process the password.
 *
 * @return bool
 *   Boolean if the password passes/fails.
 */
function password_policy_constraints_validate($pass) {
  $is_valid = preg_match('/^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%])[0-9A-Za-z!@#$%]{8,99}$/', $pass);
  if (!$is_valid) {
    $key = 'password_policy_error';
    $message = get_policy_error_message();
    return $message;
  }
  return FALSE;

}

/**
 * Password message.
 */
function get_policy_error_message() {
  $lang = \Drupal::currentUser()->getPreferredLangcode();
  $oprator = '=';
  $value = 'en';
  if ($lang != 'en') {
    $oprator = 'IN';
    $value = ['en', $lang];
  }
  $query = \Drupal::database()->select('taxonomy_term__field_translation_key', 'ubp');
  $query->join('taxonomy_term_field_data', 'tfd', 'tfd.tid =
  ubp.entity_id');
  $query->fields('ubp', ['langcode']);
  $query->fields('ubp', ['field_translation_key_value']);
  $query->condition('tfd.name', 'passwordPolicyResponseMessage', '=');
  $query->condition('ubp.langcode', $value, $oprator);
  $data = $query->execute()->fetchAllKeyed();
  if (empty($data)) {
    return t('The password does not satisfy the password policies.');
  }
  elseif (isset($data[$lang])) {
    return $data[$lang];
  }
  else {
    return $data['en'];
  }
}
