<?php

/**
 * @file
 * Create and update table.
 */

/**
 * Implements hook_update_N().
 */
function trlx_utility_update_8503() {
  // Create field storage for the 'Highlight' base field.
  $entity_manager = \Drupal::entityManager();
  $definition = $entity_manager->getFieldStorageDefinitions('menu_link_content')['trlx_menu_content'];
  $entity_manager->onFieldStorageDefinitionCreate($definition);
}
