<?php

/**
 * @file
 * Market hierarchy file.
 */

use Drupal\elx_user\Utility\UserUtility;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_views_query_alter().
 */
function elx_market_hierarchy_views_query_alter($view, $query) {
  $view_id = [
    'product_listings',
    'level_interactive_content',
    'video_listing',
    'stories_listing',
    'tools_listing',
    'video_listing_mobile',
    'welcome_message_api',
    'market_admin_dashboard',
    'dashboard',
  ];
  $current_display = [
    'rest_export_product_listings',
    'rest_export_level_interactive_content',
    'rest_export_video_listing',
    'rest_export_stories_listing',
    'rest_export_tools_listing',
    'rest_export_video_listing_mobile',
    'rest_export_welcome_message_api',
    'market_admin_dashboard_page',
    'market_admin_dashboard_page_2',
    'market_admin_dashboard_page_3',
    'dashboard_available_for_a_translation',
    'dashboard_unpublished',
    'dashboard_published',
    'dashboard_archive',
  ];
  if (in_array($view->id(), $view_id) && in_array($view->current_display, $current_display)) {
    $uid = \Drupal::currentUser()->id();
    $user_utility = new UserUtility();
    $roles = $user_utility->getUserRoles($uid);
    if ($roles) {
      // Get current user markets.
      $market = $user_utility->getMarketByUserId($uid);
      $operator = '=';
      if ($view->id() == 'dashboard') {
        $market = $user_utility->getMarketByUserId($uid, 'all');
        $market = array_column($market, 'field_default_market_target_id');
        $operator = 'IN';
      }
      // Add market table to the query.
      $query->queueTable('node__field_markets', "node_field_data", NULL, 'node__field_markets');
      // Add market condition based on the current user.
      $query->addWhere('1', 'node__field_markets.field_markets_target_id', $market, $operator);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function elx_market_hierarchy_form_alter(&$form, FormStateInterface
 $form_state, $form_id) {
  switch ($form_id) {
    case 'taxonomy_term_markets_form':
      $user_utility = new UserUtility();
      $roles = $user_utility->getUserRoles(\Drupal::currentUser()->id(), 'all',
      ['administrator']);
      if ((!$roles) &&
      (!empty($form['field_primary_language']['widget']['#default_value']))) {
        $form['field_primary_language']['#disabled'] = TRUE;
      }
      asort($form['field_primary_language']['widget']['#options']);
      asort($form['field_secondary_language']['widget']['#options']);
      unset($form['field_primary_language']['widget']['#options']['und']);
      unset($form['field_primary_language']['widget']['#options']['zxx']);
      unset($form['field_secondary_language']['widget']['#options']['und']);
      unset($form['field_secondary_language']['widget']['#options']['zxx']);
      break;

    case 'media_file_edit_form':
    case 'media_file_add_form':
    case 'entity_browser_file_entity_browser_form':
      $user_utility = new UserUtility();
      $roles = $user_utility->getUserRoles(\Drupal::currentUser()->id(), 'all',
      ['administrator']);
      // Hide pubish button on media form for non admin users.
      if (!$roles) {
        $form['#attached']['library'][] = 'elx_market_hierarchy/elx_market_admin_dashboard';
        $form['status']['#access'] = FALSE;
      }
      break;

  }
}
