<?php

/**
 * @file
 * Utility file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\trlx_utility\RedisClientBuilder;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\elx_user\Utility\UserUtility;
use Drupal\trlx_stamp\Utility\StampUtility;
use Drupal\trlx_utility\Utility\CommonUtility;

/**
 * Set node id and terms id using rest resource.
 *
 * @param object $node
 *   Node object.
 *
 * @return bool
 *   True or false.
 */
function _elx_utility_http_request($node) {
  $elx_site_url = \Drupal::config('elx_utility.settings')->get('elx_site_url');
  $uri = $elx_site_url . '/lm/api/v1/setTermsNodeData';
  $nid = $node->id();
  $tid = $node->get('field_learning_category')->getValue()[0]['target_id'];
  $client = \Drupal::httpClient();
  try {
    $request = $client->post($uri, [
      'json' => ['nid' => $nid, 'tid' => $tid],
      'headers' => ['Accept' => 'application/json'],
    ]);
    $response = (string) $request->getBody();
  }
  catch (\Exception $e) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Implements hook_form_alter().
 */
function elx_utility_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $user_utility = new UserUtility();
  // Get current user roles.
  $roles = \Drupal::currentUser()->getRoles();
  switch ($form_id) {
    case 'taxonomy_term_static_translation_form':
      $form['name']['widget'][0]['value']['#title'] = 'Key';
      $form['relations']['#access'] = FALSE;
      if (!$form_state->getFormObject()->getEntity()->isNew()) {
        $form['name']['#disabled'] = TRUE;
      }
      break;

    case 'taxonomy_term_badges_form':
      if (!$form_state->getFormObject()->getEntity()->isNew()) {
        $form['name']['#disabled'] = TRUE;
        $form['description']['#disabled'] = TRUE;
        $form['path']['#disabled'] = TRUE;
      }
      break;

    default:
  }
}

/**
 * Callback function to get default market.
 */
function elx_utility_default_market_after_build($form_element, &$form_state) {
  $uid = \Drupal::currentUser()->id();
  $user_utility = new UserUtility();
  // Get current user markets.
  $query = $user_utility->getMarketByUserId($uid, 'all');
  $current_user_mkt = array_column($query, 'field_default_market_target_id');
  $aa = 0;
  foreach ($form_element[0] as $tid => $data) {
    if (($tid[0] != '#') && is_numeric($tid)) {
      foreach ($current_user_mkt as $key => $value) {
        if (array_key_exists($value, $form_element[0][$tid]) && !isset($form_element[0][$tid][$tid . '-children'])) {
          $form_element[0][$tid][$tid]['#attributes']['data-drupal-selector'] = 'disable_other_markets_ma';
        }
        elseif (isset($form_element[0][$tid][$tid . '-children'])) {
          foreach ($form_element[0][$tid][$tid . '-children'] as $key => $children) {
            if (($key[0] != '#') && is_numeric($key)) {
              if (in_array($key, $current_user_mkt)) {
                $form_element[0][$tid][$tid . '-children'][$key][$key]['#attributes']['data-drupal-selector'] = 'disable_other_markets_ma';
              }
            }
          }
        }
      }
    }
  }
  return $form_element;
}

/**
 * Method to clear redis cache.
 */
function elx_utility_clear_redis_cache($patterns) {
  $redisObj = RedisClientBuilder::getRedisClientObject('check');
  $result = $redisObj->deleteKeyPattern($patterns);
}

/**
 * Implements hook_ENTITY_insert().
 */
function elx_utility_entity_insert(EntityInterface $entity) {
  $commonUtility = new CommonUtility();
  $env = \Drupal::config('elx_utility.settings')->get('elx_environment');
  if ($entity->getEntityTypeId() == 'node') {
    switch ($entity->gettype()) {
      case 'level_interactive_content':
        _elx_utility_http_request($entity);
        break;

      case 'stories':
        $contentSection = $entity->get('field_content_section')->referencedEntities();
        $contentSectionkey = (!empty($contentSection)) ? (array_shift($contentSection)->get('field_content_section_key')->value) : '';
        $lang_code = $entity->language()->getId();
        if (isset($contentSectionkey)) {
          switch ($contentSectionkey) {
            case 'trend':
              $patterns = [$env . ':home:tr_trends_' . $lang_code, $env . ':listing:tr_trend_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;

            case 'insiderCorner':
              $patterns = [$env . ':home:insider_corner_' . $lang_code, $env . ':listing:insider_corner_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;

            case 'sellingTips':
              $patterns = [$env . ':listing:selling_tips_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;

            case 'consumer':
              $patterns = [$env . ':listing:consumers_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;
          }
        }
        break;

      case 'product_detail':
        $brand_id = $entity->get('field_brands')->first()->getValue()['target_id'];
        $brand_key = $commonUtility->getBrandKeyByTermId($brand_id);
        $lang_code = $entity->language()->getId();
        $patterns = [$env . ':brand:factsheets_' . $brand_key . '_' . $lang_code . '*'];
        elx_utility_clear_redis_cache($patterns);
        break;

      case 'tools':
        $brand_id = $entity->get('field_brands')->first()->getValue()['target_id'];
        $brand_key = $commonUtility->getBrandKeyByTermId($brand_id);
        $lang_code = $entity->language()->getId();
        $patterns = [$env . ':brand:videos_' . $brand_key . '_' . $lang_code . '*'];
        elx_utility_clear_redis_cache($patterns);
        break;

      case 'brand_story':
        $brand_id = $entity->get('field_brands')->first()->getValue()['target_id'];
        $brand_key = $commonUtility->getBrandKeyByTermId($brand_id);
        $lang_code = $entity->language()->getId();
        $patterns = [$env . ':brand:story_' . $brand_key . '_' . $lang_code];
        elx_utility_clear_redis_cache($patterns);
        break;
    }
    // Purge Redis data.
    elx_utility_purge_redis_data($entity);
  }
  elseif ($entity->getEntityTypeId() == 'taxonomy_term') {
    $tid = $entity->id();
    $type = elx_utility_get_term_type($tid);
    if ($type == 'badges') {
      $stamp_utility = new StampUtility();
      $stamp_utility->migrateStamp();
    }
    // Purge Redis data.
    elx_utility_purge_redis_terms_data($type, $tid);
  }
  elseif ($entity->getEntityTypeId() == 'user') {
    global $base_url;
    if ($_SERVER['HTTP_REFERER'] != $base_url . '/admin/people/create' && $entity->get('status')->getValue()[0]['value'] == 1) {
      _user_mail_notify("register_admin_created", $entity);
    }
    $market_id = \Drupal::request()->query->get('userMarket');
    if (!empty($market_id)) {
      $entity->set('field_default_market', $market_id);
      $entity->save();
    }
    $uid = $entity->id();
    // Insert index in elastic_host.
    // set_user_object_elastic($uid);
  }
  elseif ($entity->getEntityTypeId() == 'entity_subqueue') {
    // Purge Redis data.
    if ($entity->id() == 'insider_corner_hompage') {
      $patterns = [$env . ':home:insider_corner_' . '*'];
      elx_utility_clear_redis_cache($patterns);
    }
    elx_utility_purge_redis_data($entity);
  }
  elseif ($entity->getEntityTypeId() == 'menu_link_content') {
    if ($entity->getMenuName() == 'privacy-menu' || $entity->getMenuName() == 'social-media' || $entity->getMenuName() == 'header-menu' || $entity->getMenuName() == 'main') {
      // Purge Redis data.
      elx_utility_purge_redis_data($entity);
    }

  }
}

/**
 * Implements hook_ENTITY_update().
 */
function elx_utility_entity_update(EntityInterface $entity) {
  $commonUtility = new CommonUtility();
  $env = \Drupal::config('elx_utility.settings')->get('elx_environment');
  if ($entity->getEntityTypeId() == 'node') {
    switch ($entity->gettype()) {
      case 'level_interactive_content':
        _elx_utility_http_request($entity);
        break;

      case 'stories':
        $contentSection = $entity->get('field_content_section')->referencedEntities();
        $contentSectionkey = (!empty($contentSection)) ? (array_shift($contentSection)->get('field_content_section_key')->value) : '';
        $lang_code = $entity->language()->getId();
        if (isset($contentSectionkey)) {
          switch ($contentSectionkey) {
            case 'trend':
              $patterns = [$env . ':home:tr_trends_' . $lang_code, $env . ':listing:tr_trend_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;

            case 'insiderCorner':
              $patterns = [$env . ':home:insider_corner_' . $lang_code, $env . ':listing:insider_corner_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;

            case 'sellingTips':
              $patterns = [$env . ':listing:selling_tips_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;

            case 'consumer':
              $patterns = [$env . ':listing:consumers_' . $lang_code . '*'];
              elx_utility_clear_redis_cache($patterns);
              break;

          }
        }
        break;

      case 'product_detail':
        $brand_id = $entity->get('field_brands')->first()->getValue()['target_id'];
        $brand_key = $commonUtility->getBrandKeyByTermId($brand_id);
        $lang_code = $entity->language()->getId();
        $patterns = [$env . ':brand:factsheets_' . $brand_key . '_' . $lang_code . '*'];
        elx_utility_clear_redis_cache($patterns);
        break;

      case 'tools':
        $brand_id = $entity->get('field_brands')->first()->getValue()['target_id'];
        $brand_key = $commonUtility->getBrandKeyByTermId($brand_id);
        $lang_code = $entity->language()->getId();
        $patterns = [$env . ':brand:videos_' . $brand_key . '_' . $lang_code . '*'];
        elx_utility_clear_redis_cache($patterns);
        break;

      case 'brand_story':
        $brand_id = $entity->get('field_brands')->first()->getValue()['target_id'];
        $brand_key = $commonUtility->getBrandKeyByTermId($brand_id);
        $lang_code = $entity->language()->getId();
        $patterns = [$env . ':brand:story_' . $brand_key . '_' . $lang_code];
        elx_utility_clear_redis_cache($patterns);
        break;
    }
    // Purge Redis data.
    elx_utility_purge_redis_data($entity);
  }
  elseif ($entity->getEntityTypeId() == 'taxonomy_term') {
    $tid = $entity->id();
    $type = elx_utility_get_term_type($tid);
    if ($type == 'badges') {
      $stamp_utility = new StampUtility();
      $stamp_utility->migrateStamp();
    }
    // Purge Redis data.
    elx_utility_purge_redis_terms_data($type, $tid);
  }
  elseif ($entity->getEntityTypeId() == 'user') {
    $uid = $entity->id();
    // Insert index in elastic_host.
    elx_utility_purge_redis_data($entity);
  }
  elseif ($entity->getEntityTypeId() == 'entity_subqueue') {
    // Purge Redis data.
    if ($entity->id() == 'insider_corner_hompage') {
      $patterns = [$env . ':home:insider_corner_' . '*'];
      elx_utility_clear_redis_cache($patterns);
    }

    elx_utility_purge_redis_data($entity);
  }
  elseif ($entity->getEntityTypeId() == 'menu_link_content') {
    if ($entity->getMenuName() == 'privacy-menu' || $entity->getMenuName() == 'social-media' || $entity->getMenuName() == 'header-menu' || $entity->getMenuName() == 'main') {
      // Purge Redis data.
      elx_utility_purge_redis_data($entity);
    }
  }
}

/**
 * Implements hook_ENTITY_delete().
 */
function elx_utility_entity_delete(EntityInterface $entity) {
  $env = \Drupal::config('elx_utility.settings')->get('elx_environment');
  if ($entity->getEntityTypeId() == 'node') {
    switch ($entity->gettype()) {
      case 'level_interactive_content':
        _elx_utility_http_delete_request($entity);
        break;
      case 'stories':
       $patterns = [$env . ':home:tr_trends_' . '*'];
        elx_utility_clear_redis_cache($patterns);
        break;
    }
    // Purge Redis data.
    elx_utility_purge_redis_data($entity);
    $response = new RedirectResponse('/dashboard/published');
    $response->send();
    return;
  }
  elseif ($entity->getEntityTypeId() == 'taxonomy_term') {
    $tid = $entity->id();
    $type = $entity->bundle();
    if ($type == 'badges') {
      $stamp_utility = new StampUtility();
      $stamp_utility->migrateStamp();
    }
    // Purge Redis data.
    elx_utility_purge_redis_terms_data($type, $tid);
  }
  elseif ($entity->getEntityTypeId() == 'entity_subqueue') {
    // Purge Redis data.
    if ($entity->id() == 'insider_corner_hompage') {
      $patterns = [$env . ':home:insider_corner_' . '*'];
      elx_utility_clear_redis_cache($patterns);
    }
    // Purge Redis data.
    elx_utility_purge_redis_data($entity);
  }
  elseif ($entity->getEntityTypeId() == 'user') {
    // Purge Elastic data.
    elx_utility_purge_elastic_data($entity);
  }
  elseif ($entity->getEntityTypeId() == 'menu_link_content') {
    if ($entity->getMenuName() == 'privacy-menu' || $entity->getMenuName() == 'social-media' || $entity->getMenuName() == 'header-menu' || $entity->getMenuName() == 'main') {
      // Purge Redis data.
      elx_utility_purge_redis_data($entity);
    }
  }
}

/**
 * Purge user data from elastic.
 */
function elx_utility_purge_elastic_data(EntityInterface $entity) {
  $uid = $entity->id();
  try {
    $elx_site_url = \Drupal::config('elx_utility.settings')->get('elx_site_url');
    $response = \Drupal::httpClient()->get($elx_site_url . "/lm/api/v1/purgeElasticUser?_format=json&uid=" . $uid, ['headers' => ['Accept' => 'application/json']]);

    return;
  }
  catch (RequestException $e) {
    return $e->getMessage();
  }
}

/**
 * Check and prepare redis pattern to delete.
 */
function elx_utility_purge_redis_data(EntityInterface $entity) {
  $pattern = elx_utility_get_redis_pattern($entity);
  if (!empty($pattern)) {
    try {
      $redisObj = RedisClientBuilder::getRedisClientObject('check');
      $result = $redisObj->deleteKeyPattern($pattern);
    }
    catch (\Exception $e) {
      \Drupal::logger('elx_utility')->error('Redis connection failed.');
    }
  }
}

/**
 * Check and prepare redis pattern to delete.
 */
function elx_utility_purge_redis_terms_data($type, $tid) {
  $pattern = elx_utility_get_redis_terms_pattern($type, $tid);
  if (!empty($pattern)) {
    try {
      $redisObj = RedisClientBuilder::getRedisClientObject('check');
      $result = $redisObj->deleteKeyPattern($pattern);
    }
    catch (\Exception $e) {
      \Drupal::logger('elx_utility')->error('Redis connection failed.');
    }
  }
}

/**
 * Check for blog content field then returns redis pattern for deletion.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity.
 *
 * @return string
 *   The pattern of the cached key to be deleted.
 */
function elx_utility_get_redis_pattern(EntityInterface $entity) {
  $lang_code = $entity->language()->getId();
  $pattern = [];
  $env = \Drupal::config('elx_utility.settings')->get('elx_environment');
  if ($entity->getEntityTypeId() == 'node' && !empty($entity->id())) {
    $entity_type = $entity->gettype();
    if ($entity_type == 'products_carousel') {
      $pattern[] = implode(':', [$env, 'productsCarousel', $lang_code . '*']);

      return $pattern;
    }
    $uid = \Drupal::currentUser()->id();
    $entity_id = $entity->id();
    if ($entity_type == 'product_detail') {
      $pattern[] = implode(':', [$env, 'productDetails*']);
      $pattern[] = implode(':', [$env, 'productCategories*']);
      $pattern[] = implode(':', [$env, 'productListings*']);
      $pattern[] = implode(':', [$env, 'globalBrowseProducts*']);
      $pattern[] = implode(':', [$env, 'browseProductsMarketWise*']);
      $pattern[] = implode(':', [$env, 'spotlightSection*']);
      $pattern[] = implode(':', [$env, 'spotlightSectionMarketWise*']);
    }
    elseif ($entity_type == 'level_interactive_content') {
      $pattern[] = implode(':', [$env, 'levelInteractiveContent*']);
      $pattern[] = implode(':', [$env, 'levelInteractiveTermsContent*']);
      $pattern[] = implode(':', [$env, 'learningLevels*']);
      $pattern[] = implode(':', [$env, 'exploreLearningLevels*']);
      $pattern[] = implode(':', [$env, 'spotlightSection*']);
      $pattern[] = implode(':', [$env, 'spotlightSectionMarketWise*']);
    }
    elseif ($entity_type == 'tools') {
      $pattern[] = implode(':', [$env, 'videoCategory*']);
      $pattern[] = implode(':', [$env, 'videoListings*']);
      $pattern[] = implode(':', [$env, 'videoListingMobile*']);
      $pattern[] = implode(':', [$env, 'videoDetails*']);
      $pattern[] = implode(':', [$env, 'spotlightSection*']);
      $pattern[] = implode(':', [$env, 'spotlightSectionMarketWise*']);
    }
    elseif ($entity_type == 'stories') {
      $pattern[] = implode(':', [$env, 'trendListing*']);
      $pattern[] = implode(':', [$env, 'storyDetail*']);
      $pattern[] = implode(':', [$env, 'spotlightSection*']);
      $pattern[] = implode(':', [$env, 'spotlightSectionMarketWise*']);
      $pattern[] = implode(':', [$env, 'storiesTrendingSection*']);
      $pattern[] = implode(':', [$env, 'storiesTrendingSectionMarketWise*']);
    }
    elseif ($entity_type == 't_c') {
      $pattern[] = implode(':', [$env . '_t_c', 'detail*']);
    }
    elseif ($entity_type == 'brand_story') {
      $pattern[] = implode(':', [$env . 'brandStoryDetails*']);
    }
  }
  elseif ($entity->getEntityTypeId() == 'entity_subqueue' && !empty($entity->getQueue())) {
    if ($entity->getQueue()->id() == 'stories' || $entity->getQueue()->id() == 'stories_market_wise') {
      $pattern[] = implode(':', [$env, 'storiesTrendingSection*']);
      $pattern[] = implode(':', [$env, 'storiesTrendingSectionMarketWise*']);
    }
    elseif ($entity->getQueue()->id() == 'spotlight' || $entity->getQueue()->id() == 'spotlight_market_wise') {
      $pattern[] = implode(':', [$env, 'spotlightSection*']);
      $pattern[] = implode(':', [$env, 'spotlightSectionMarketWise*']);
    }
    elseif ($entity->getQueue()->id() == 'explore_learning_levels') {
      $pattern[] = implode(':', [$env, 'exploreLearningLevels*']);
    }
    elseif ($entity->getQueue()->id() == 'browse_products' || $entity->getQueue()->id() == 'browse_products_market_wise') {
      $pattern[] = implode(':', [$env, 'globalBrowseProducts*']);
      $pattern[] = implode(':', [$env, 'browseProductsMarketWise*']);
    }
  }
  elseif ($entity->getEntityTypeId() == 'menu_link_content') {
    if ($entity->getMenuName() == 'privacy-menu' || $entity->getMenuName() == 'social-media') {
      // Purge redis data.
      $pattern[] = implode(':', [$env, 'footerMenu*']);
    }
    elseif ($entity->getMenuName() == 'header-menu') {
      // Purge redis data.
      $pattern[] = implode(':', [$env, 'headerMenu*']);
    }
    elseif ($entity->getMenuName() == 'main') {
      // Purge redis data.
      $pattern[] = implode(':', [$env, 'navigationMenu*']);
    }
  }
  elseif ($entity->getEntityTypeId() == 'user') {
    // Purge Redis data.
    $pattern[] = implode(':', [$env, 'headerMenu*']);
  }
  // For non blog related content type : return entity type as a key for redis.
  else {
    $pattern = $entity_type;
  }

  return $pattern;
}

/**
 * Check for taxonomy term content then returns redis pattern for deletion.
 *
 * @param string $type
 *   Type of taxonomy term.
 *
 * @return string
 *   The pattern of the cached key to be deleted.
 */
function elx_utility_get_redis_terms_pattern($type, $tid) {
  $uid = \Drupal::currentUser()->id();
  $env = \Drupal::config('elx_utility.settings')->get('elx_environment');
  $pattern = [];
  if ($type == 'learning_category') {
    $pattern[] = implode(':', [$env, 'levelInteractiveContent*']);
    $pattern[] = implode(':', [$env, 'learningLevels*']);
    $pattern[] = implode(':', [$env, 'levelInteractiveTermsContent*']);
    $pattern[] = implode(':', [$env, 'exploreLearningLevels*']);
  }
  elseif ($type == 'videos') {
    $pattern[] = implode(':', [$env, 'videoListings*']);
    $pattern[] = implode(':', [$env, 'videoListingMobile*']);
    $pattern[] = implode(':', [$env, 'videoDetails*']);
    $pattern[] = implode(':', [$env, 'videoCategory*']);
  }
  elseif ($type == 'product_category') {
    $pattern[] = implode(':', [$env, 'productCategories*']);
    $pattern[] = implode(':', [$env, 'productListings*']);
    $pattern[] = implode(':', [$env, 'productDetails*']);
  }

  return $pattern;
}

/**
 * Get type of taxonomy term.
 *
 * @param int $tid
 *   Id of taxonomy term.
 *
 * @return string
 *   The type of the taxonomy term.
 */
function elx_utility_get_term_type($tid) {
  $type = db_select('taxonomy_term_field_data', 'tfd')
    ->fields('tfd', ['vid'])
    ->condition('tfd.tid', $tid, '=')
    ->execute()->fetchAssoc();
  return $type['vid'];
}

/**
 * Set node id and terms id using rest resource.
 *
 * @param object $node
 *   Node object.
 *
 * @return json
 *   API url to update the data in DB.
 */
function _elx_utility_http_delete_request($node) {
  $elx_site_url = \Drupal::config('elx_utility.settings')->get('elx_site_url');
  $uri = $elx_site_url . '/lm/api/v1/deleteTermsNodeData';
  $nid = $node->id();
  $tid = $node->get('field_learning_category')->getValue()[0]['target_id'];
  $client = \Drupal::httpClient();
  try {
    $request = $client->post($uri, [
      'json' => ['nid' => $nid, 'tid' => $tid],
      'headers' => ['Accept' => 'application/json'],
    ]);
    $response = json_decode($request->getBody());
  }
  catch (\Exception $e) {
    return $e->getMessage();
  }

  return TRUE;
}

/**
 * Implements hook_mail_alter().
 */
function elx_utility_mail_alter(&$message) {
  // Add html in mail header.
  $message['headers']['content-type'] = 'text/html';
}

/**
 * Implements hook_preprocess_views_view_field().
 */
function elx_utility_preprocess_views_view_field(&$variables) {
  global $base_url;
  $variables['front_end_url'] = \Drupal::config('elx_utility.settings')->get('elx_front_end_url');
  $variables['site_base_url'] = $base_url;
}
