<?php

/**
 * @file
 * Bul mail module.
 */

use Drupal\file\Entity\File;

/**
 * Implements hook_mail().
 */
function elx_bulk_mail_mail($key, &$message, $params) {
  switch ($key) {
    case 'send_bulk_mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Fetch file uri.
 *
 * @param string $fid
 *   File id.
 *
 * @return string
 *   File uri.
 */
function _elx_file_uri($fid) {
  $file = File::load($fid);

  return $file->getFileUri();
}

/**
 * Fetch file name.
 *
 * @param string $fid
 *   File id.
 *
 * @return string
 *   File name.
 */
function _elx_file_name($fid) {
  $file = File::load($fid);

  return $file->getFilename();
}
