<?php

/**
 * @file
 * ELX stories module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\elx_lang_translation\Utility\LangUtility;
use Drupal\elx_user\Utility\UserUtility;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function elx_stories_form_alter(&$form, FormStateInterface $form_state,
$form_id) {
  if ($form_id == 'node_stories_form' || $form_id == 'node_stories_edit_form') {
    global $base_url;
    $lang_utility = new LangUtility();
    $user_utility = new UserUtility();
    // Get form object.
    $entity = $form_state->getFormObject()->getEntity();
    // Fetch translation langcode.
    $quiz_langcode = $entity->get('default_langcode')->getLangcode();
    // Fetch quiz node id.
    $quiz_id = $entity->get('field_quiz')->getValue()[0]['target_id'];
    // Fetch all translated node langcode by quiz id.
    $node_lang = $lang_utility->getTranslationLanguageByNid($quiz_id);
    $roles = $user_utility->getUserRoles(\Drupal::currentUser()->id(), 'all',
     ['el_regional_market_admin']);
    if ($roles) {
      $form['field_quiz']['#disabled'] = TRUE;
    }
    $uri = '';
    if (empty($quiz_id) && !empty($roles)) {
      $uri = '';
    }
    elseif (empty($quiz_id) && empty($roles)) {
      $button_text = 'Add Quiz';
      $uri = '/node/add/quiz';
    }
    elseif ($quiz_langcode == 'en') {
      $button_text = 'Edit';
      $uri = '/node/' . $quiz_id . '/edit';
    }
    elseif (in_array($quiz_langcode, $node_lang)) {
      $button_text = 'Edit Translation';
      $uri = '/' . $quiz_langcode . '/node/' . $quiz_id . '/edit';
    }
    elseif (!empty($quiz_id)) {
      $button_text = 'Add Translation';
      $uri = '/' . $quiz_langcode . '/node/' . $quiz_id
      . '/translations/add/en/' . $quiz_langcode;
    }
    if (!empty($uri)) {
      $url = $base_url . $uri . '?destination=' .
      \Drupal::service('path.current')->getPath();
      $url = Url::fromUri($url);
      $link_options = [
        'attributes' => [
          'class' => [
            'button',
            'button-action',
            'button--primary button--small',
          ],
          'target' => [
            '_blank',
          ],
        ],
      ];
      $url->setOptions($link_options);
      $link = \Drupal::l(t($button_text), $url);
      $form['field_quiz']['#prefix'] = "<div class='custom-wrapper'>";
      $form['field_quiz']['#suffix'] = $link . "</div>";
    }
  }
}
