<?php

/**
 * @file
 * User module file.
 */

/**
 * Implements hook_menu_local_tasks_alter().
 */
function trlx_user_menu_local_tasks_alter(&$data, $route_name) {
  // Check route for user listing page
  if ($route_name == 'entity.user.collection') {
    $currentAccount = \Drupal::currentUser();
    $roles = $currentAccount->getRoles();
    if (in_array('el_regional_market_admin', $roles) || in_array('el_nyo_global_education_system_admin', $roles)) {
      // Permission and Roles tab unset for MA and GA
      unset($data['tabs'][0]['user.admin_permissions']);
      unset($data['tabs'][0]['entity.user_role.collection']);
    }
  }
}
 